### ISSUE TITLE
Unexpected keyword arg bot

### ISSUE THREAD

**Issue by NexusLove** [DrkTheDon/BlackDC#3]
Traceback (most recent call last):                     File "/data/data/com.termux/files/home/BlackDC/main.py", line 206, in <module>
    bot.run(TOKEN, bot=False)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/client.py", line 631, in run
    return future.result()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/client.py", line 610, in runner
    await self.start(*args, **kwargs)                  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/discord/client.py", line 571, in start
    raise TypeError("unexpected keyword argument(s) %s" % list(kwargs.keys()))                            TypeError: unexpected keyword argument(s) ['bot']

**Comment by DrkTheDon** [comment]
btw are you running termux on android?

**Comment by DrkTheDon** [comment]
Termux devices doesnt really work for me, its really buggy. I tested it out on UsErLand: Ubuntu in android and it worked with a minor bug.
